server:
  port:80
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authors?characterEncoding=utf8
    username:root
    password:root
    database:MYSQL
    show-sql:true
    hibernate:
      ddl-auto:update
      naming-strategy:org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect